version: 1
applications:
  - appRoot: my-salesforce-user-app/frontend
    frontend:
      phases:
        preBuild:
          commands:
            # https://docs.aws.amazon.com/ja_jp/amplify/latest/userguide/edit-build-settings.html#navigating-to-a-subfolder
            - yarn install
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: ".next"
        files:
          - '**/*'
      cache:
        paths:
          - .next/cache/**/*
          - node_modules/**/*
