version: 1
frontend:
  phases:
    preBuild:
      commands:
        # https://docs.aws.amazon.com/ja_jp/amplify/latest/userguide/edit-build-settings.html#navigating-to-a-subfolder
        - cd frontend
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: ".next"
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
